name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.8.0
    
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -coverprofile cover.out
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: cover.out
        flags: unittests
        name: codecov-umbrella
        verbose: true
